# Generated by Django 5.1.3 on 2024-11-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvetka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updete',
            new_name='update',
        ),
    ]
